import React, { useState } from 'react';
import { Plus, Check, X, Send, Download, KeyRound, UserRoundCog, Search, ArrowLeft, CheckCircle2, Clock3 } from 'lucide-react';
import { jalaliToday, jalaliToISO, dayInterval } from '@residency/domain';
import { api } from './api';
import { useApp, Button, Field, Badge, Empty, Modal, PageTitle, FormActions, JalaliField, useResource, ResourceState } from './ui';
import { AttendanceTable } from './sessions';

export function PasswordForm({ onDone }) {
  const { t, run, signedIn, flash } = useApp();
  return <form onSubmit={e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const auth = await api('/auth/password', { method: 'POST', body }); await signedIn(auth); flash(t('saved')); onDone?.(); }); }}><Field label={t('currentPassword')}><input type="password" name="currentPassword" autoComplete="current-password" required maxLength={128}/></Field><Field label={t('newPassword')} hint={t('passwordHint')}><input type="password" name="password" autoComplete="new-password" required minLength={12} maxLength={128}/></Field><FormActions label="passwordChange"/></form>;
}

export function LeavePage() {
  const { t, user, online, run, refresh, date, time, sessions } = useApp(); const { data, error } = useResource('/leave');
  const [newLeave, setNewLeave] = useState(false); const [decision, setDecision] = useState(null); const [filter, setFilter] = useState('all');
  const visible = (data || []).filter(l => filter === 'all' || l.status === filter);
  return <><PageTitle title={t('leave')} subtitle={t('leaveSub')} action={user.kind === 'student' && <Button disabled={!online} onClick={() => setNewLeave(true)}><Plus size={18}/>{t('newLeave')}</Button>}/><div className="toolbar"><div className="tabs">{['all', 'pending_professor','pending_admin','approved'].map(key => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{t(key)}</button>)}</div></div>
    <ResourceState data={data} error={error}>{visible.length === 0 ? <div className="panel"><Empty text="noRequests"/></div> : <div className="leave-grid">{visible.map(l => {
      const canDecide = (user.kind === 'professor' && l.status === 'pending_professor') || (user.kind === 'admin' && l.status === 'pending_admin');
      return <article key={l._id} className="panel leave-card"><div className="leave-card-head"><div><span className="eyebrow">{t(l.type)}</span><h2>{user.kind === 'student' ? date(l.startAt) : l.studentName}</h2></div><Badge value={l.status}/></div><p className="muted">{date(l.startAt)} · {time(l.startAt)} — {date(l.endAt)} · {time(l.endAt)}</p>{l.type === 'session' && <p>{sessions.find(s => s._id === l.sessionId)?.title || t('session')}</p>}{l.reason && <p className="leave-reason">{l.reason}</p>}<div className="approval-track"><div className={l.professorDecision?.decision === 'approve' ? 'complete' : ''}>{l.professorDecision?.decision === 'approve' ? <CheckCircle2 size={19}/> : <Clock3 size={19}/>}<span>{t('professor')}<small>{l.professorName}</small></span></div><span className="track-line"/><div className={l.status === 'approved' ? 'complete' : ''}>{l.status === 'approved' ? <CheckCircle2 size={19}/> : <Clock3 size={19}/>}<span>{t('admin')}<small>{t(l.status === 'approved' ? 'approved' : l.status === 'admin_denied' ? 'admin_denied' : 'pending')}</small></span></div></div>{l.professorDecision?.note && <p className="muted">{t('professor')}: {l.professorDecision.note}</p>}{l.adminDecision?.note && <p className="muted">{t('admin')}: {l.adminDecision.note}</p>}{canDecide && <div className="button-row"><Button onClick={() => setDecision({ leave: l, value: 'approve' })}><Check size={16}/>{t('approve')}</Button><Button variant="danger" onClick={() => setDecision({ leave: l, value: 'deny' })}><X size={16}/>{t('deny')}</Button></div>}</article>;
    })}</div>}</ResourceState>
    {newLeave && <LeaveForm onClose={() => setNewLeave(false)}/>}
    {decision && <Modal title={t(decision.value)} onClose={() => setDecision(null)}><p>{decision.leave.studentName} · {date(decision.leave.startAt)}</p><form onSubmit={e => { e.preventDefault(); const note = new FormData(e.currentTarget).get('note'); run(async () => { await api(`/leave/${decision.leave._id}/decision`, { method: 'POST', body: { decision: decision.value, version: decision.leave.version, note } }); setDecision(null); refresh(); }); }}><Field label={t('decisionNote')}><textarea name="note" maxLength={1000} rows={3}/></Field><FormActions onCancel={() => setDecision(null)} label={decision.value}/></form></Modal>}
  </>;
}
function LeaveForm({ onClose }) {
  const { t, user, directory, sessions, run, flash, refresh, date } = useApp(); const [type, setType] = useState('day');
  const ownSessions = sessions.filter(s => s.participations.some(p => p.status === 'approved' && p.confirmed && p.studentIds.includes(user._id)));
  return <Modal title={t('newLeave')} onClose={onClose}><p className="muted">{t('leaveSub')}</p><form onSubmit={e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); run(async () => {
    const body = { type, professorId: values.professorId, reason: values.reason };
    if (type === 'day') body.date = values.date;
    if (type === 'session') body.sessionId = values.sessionId;
    if (type === 'hourly') { body.startAt = jalaliToISO(values.startDate, values.startTime); body.endAt = jalaliToISO(values.endDate, values.endTime); }
    await api('/leave', { method: 'POST', body }); flash(t('saved')); onClose(); refresh();
  }); }}><Field label={t('leaveType')}><select value={type} onChange={e => setType(e.target.value)}>{['day','session','hourly'].map(k => <option key={k} value={k}>{t(k)}</option>)}</select></Field>
    {type === 'day' && <JalaliField defaultValue={jalaliToday()}/>}
    {type === 'session' && <Field label={t('session')}><select name="sessionId" required><option value="">—</option>{ownSessions.map(s => <option key={s._id} value={s._id}>{s.title} · {date(s.startAt)}</option>)}</select></Field>}
    {type === 'hourly' && <div className="form-grid"><JalaliField name="startDate" label={t('startDate')} defaultValue={jalaliToday()}/><Field label={t('startTime')}><input name="startTime" type="time" required defaultValue="08:00"/></Field><JalaliField name="endDate" label={t('endDate')} defaultValue={jalaliToday()}/><Field label={t('endTime')}><input name="endTime" type="time" required defaultValue="09:00"/></Field></div>}
    <Field label={t('chosenProfessor')}><select name="professorId" required><option value="">—</option>{directory.professors.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></Field><Field label={t('reason')}><textarea name="reason" rows={3} maxLength={2000}/></Field><p className="note">{t('leaveApprovedNote')}</p><FormActions onCancel={onClose} label="submit"/>
  </form></Modal>;
}

export function PeoplePage() {
  const { t, user, online, run, refresh, flash, busy } = useApp(); const resource = useResource(user.kind === 'admin' || user.isRep ? '/users' : null);
  const [creating, setCreating] = useState(false); const [credentials, setCredentials] = useState(null); const [search, setSearch] = useState('');
  if (user.kind !== 'admin' && !user.isRep) return <Empty text="noAccess"/>;
  const people = (resource.data || []).filter(p => `${p.name} ${p.username}`.toLowerCase().includes(search.toLowerCase()));
  const approve = (person, decision) => run(async () => { const result = await api(`/users/${person._id}/decision`, { method: 'POST', body: { decision } }); if (result.temporaryPassword) setCredentials({ username: person.username, password: result.temporaryPassword }); refresh(); });
  const change = (person, body) => run(async () => { if (body.status === 'suspended' && !confirm(t('confirmSuspend'))) return; await api(`/users/${person._id}`, { method: 'PATCH', body }); refresh(); });
  const reset = person => run(async () => { if (!confirm(t('confirmReset'))) return; const result = await api(`/users/${person._id}/password-reset`, { method: 'POST', body: {} }); setCredentials({ username: person.username, password: result.temporaryPassword }); });
  return <><PageTitle title={t('residents')} subtitle={t('residentsSub')} action={<Button disabled={!online} onClick={() => setCreating(true)}><Plus size={18}/>{t(user.kind === 'admin' ? 'addAccount' : 'addResident')}</Button>}/><div className="toolbar"><span className="muted">{people.length} {t('residents')}</span><label className="search"><Search size={17}/><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e => setSearch(e.target.value)}/></label></div><ResourceState {...resource}><div className="panel">{people.length === 0 ? <Empty text="noPeople"/> : <div className="table-scroll"><table><thead><tr><th>{t('name')}</th><th>{t('role')}</th><th>{t('status')}</th>{user.kind === 'admin' && <th>{t('action')}</th>}</tr></thead><tbody>{people.map(p => <tr key={p._id}><td><div className="person-cell"><span className="avatar pale">{p.name[0]}</span><div><strong>{p.name}</strong><small dir="ltr">{p.username}</small></div></div></td><td><Badge value={p.isRep ? 'rep' : p.kind}/></td><td><Badge value={p.status}/></td>{user.kind === 'admin' && <td><div className="button-row small-actions">{p.status === 'pending' ? <><Button disabled={busy} onClick={() => approve(p,'approve')}>{t('approve')}</Button><Button disabled={busy} variant="danger" onClick={() => approve(p,'reject')}>{t('reject')}</Button></> : p.kind === 'student' && ['active','suspended'].includes(p.status) ? <>{p.status === 'active' && <><Button variant="secondary" disabled={busy} onClick={() => change(p,{ isRep: !p.isRep })}><UserRoundCog size={15}/>{t(p.isRep ? 'revokeRep' : 'grantRep')}</Button><button className="icon-button" title={t('resetPassword')} aria-label={`${t('resetPassword')}: ${p.name}`} disabled={busy} onClick={() => reset(p)}><KeyRound size={17}/></button></>}<Button variant="ghost" disabled={busy} onClick={() => change(p,{ status: p.status === 'active' ? 'suspended' : 'active' })}>{t(p.status === 'active' ? 'suspend' : 'activate')}</Button></> : null}</div></td>}</tr>)}</tbody></table></div>}</div></ResourceState>
    {creating && <Modal title={t(user.kind === 'admin' ? 'addAccount' : 'addResident')} onClose={() => setCreating(false)}><form onSubmit={e => { e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const result = await api('/users', { method: 'POST', body: { ...form, kind: form.kind || 'student' } }); if (result.temporaryPassword) setCredentials({ username: form.username, password: result.temporaryPassword }); else flash(t('proposed')); setCreating(false); refresh(); }); }}><Field label={t('name')}><input name="name" required minLength={2} maxLength={120}/></Field><Field label={t('username')} hint={t('usernameHint')}><input name="username" dir="ltr" required pattern="[a-zA-Z0-9][a-zA-Z0-9._\-]{2,39}"/></Field>{user.kind === 'admin' && <Field label={t('role')}><select name="kind"><option value="student">{t('student')}</option><option value="professor">{t('professor')}</option></select></Field>}<FormActions onCancel={() => setCreating(false)}/></form></Modal>}
    {credentials && <Modal title={t('temporaryPassword')} onClose={() => setCredentials(null)}><p className="note">{t('credentialsNote')}</p><Field label={t('username')}><input readOnly dir="ltr" value={credentials.username}/></Field><Field label={t('temporaryPassword')}><input readOnly dir="ltr" value={credentials.password}/></Field><div className="form-actions"><Button onClick={() => run(async () => { await navigator.clipboard.writeText(`${credentials.username}\n${credentials.password}`); flash(t('copied')); })}>{t('copy')}</Button><Button variant="secondary" onClick={() => setCredentials(null)}>{t('close')}</Button></div></Modal>}
  </>;
}

export function MessagesPage() {
  const { t, user, directory, online, run, refresh, date, time, busy } = useApp(); const allowed = ['admin','professor'].includes(user.kind);
  const threads = useResource(allowed ? '/threads' : null); const [selected, setSelected] = useState(null); const messages = useResource(selected ? `/threads/${selected._id}/messages` : null); const [creating, setCreating] = useState(false); const [reply, setReply] = useState('');
  if (!allowed) return <Empty text="noAccess"/>;
  return <><PageTitle title={t('messages')} subtitle={t('messagesSub')} action={user.kind === 'professor' && <Button disabled={!online} onClick={() => setCreating(true)}><Plus size={18}/>{t('newMessage')}</Button>}/><ResourceState {...threads}><div className="messages-layout panel"><div className={`thread-list ${selected ? 'has-selection' : ''}`}>{threads.data?.length === 0 ? <Empty text="noMessages"/> : threads.data?.map(thread => <button key={thread._id} className={selected?._id === thread._id ? 'selected' : ''} onClick={() => setSelected(thread)}><strong>{thread.subject}</strong><span>{thread.professorName} · {t('year')} {directory.cohorts.find(c => c._id === thread.cohortId)?.year}</span><small>{date(thread.updatedAt)}</small></button>)}</div><div className={`conversation ${selected ? 'visible' : ''}`}>{!selected ? <Empty text="noMessages"/> : <><div className="conversation-head"><button className="icon-button" onClick={() => setSelected(null)} aria-label={t('back')}><ArrowLeft size={18}/></button><h2>{selected.subject}</h2></div><ResourceState {...messages}><div className="message-list">{messages.data?.map(m => <div className={`message-bubble ${m.authorId === user._id ? 'mine' : ''}`} key={m._id}><p>{m.text}</p><small>{date(m.createdAt)} · {time(m.createdAt)}</small></div>)}</div></ResourceState><form className="reply-form" onSubmit={e => { e.preventDefault(); run(async () => { await api(`/threads/${selected._id}/messages`, { method: 'POST', body: { text: reply } }); setReply(''); refresh(); }); }}><textarea aria-label={t('reply')} placeholder={t('reply')} value={reply} onChange={e => setReply(e.target.value)} required maxLength={4000}/><Button type="submit" disabled={busy || !online}><Send size={17}/>{t('send')}</Button></form></>}</div></div></ResourceState>
    {creating && <Modal title={t('newMessage')} onClose={() => setCreating(false)}><form onSubmit={e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const thread = await api('/threads', { method: 'POST', body }); setCreating(false); setSelected(thread); refresh(); }); }}><Field label={t('cohort')}><select name="cohortId" required>{directory.cohorts.map(c => <option key={c._id} value={c._id}>{t('year')} {c.year}</option>)}</select></Field><Field label={t('subject')}><input name="subject" required minLength={2} maxLength={160}/></Field><Field label={t('message')}><textarea name="text" required maxLength={4000} rows={5}/></Field><FormActions onCancel={() => setCreating(false)} label="send"/></form></Modal>}
  </>;
}

function csvCell(value) { const text = String(value ?? ''); return '"' + (/^[=+\-@\t\r]/.test(text) ? "'" : '') + text.replaceAll('"','""') + '"'; }
export function ReportsPage() {
  const { t, online, run, directory, date, time, busy } = useApp(); const [reports, setReports] = useState(null);
  const exportCsv = () => {
    const rows = [[t('session'),t('date'),t('student'),t('actor'),t('role'),t('status'),t('recorded'),t('received'),t('leaveEffect'),t('overrideReason')]];
    for (const report of reports) for (const row of report.rows) for (const o of row.observations.length ? row.observations : [{}]) rows.push([report.session.title, `${date(report.session.startAt)} ${time(report.session.startAt)}`,row.student.name,o.observerName,o.role ? t(o.role) : '',o.status ? t(o.status) : t('unmarked'),o.recordedAt ? `${date(o.recordedAt)} ${time(o.recordedAt)}` : '',o.receivedAt ? `${date(o.receivedAt)} ${time(o.receivedAt)}` : '',row.leave ? t(row.leave.status) : '',row.leave?.override?.reason || '']);
    const blob = new Blob(['\ufeff' + rows.map(row => row.map(csvCell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'cohort-attendance.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000);
  };
  return <><PageTitle title={t('reports')} subtitle={t('reportSub')} action={reports?.length > 0 && <Button variant="secondary" onClick={exportCsv}><Download size={17}/>{t('exportCsv')}</Button>}/><form className="panel report-filters" onSubmit={e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { const params = new URLSearchParams({ startAt: dayInterval(values.from).startAt, endAt: dayInterval(values.until).endAt }); setReports(await api(`/reports/attendance?${params}`)); }); }}><JalaliField name="from" label={t('from')} defaultValue={jalaliToday()}/><JalaliField name="until" label={t('until')} defaultValue={jalaliToday()}/><Button type="submit" disabled={!online || busy}>{t('generate')}</Button></form>{reports === null ? <div className="panel"><Empty text="reportEmpty"/></div> : reports.length === 0 ? <div className="panel"><Empty/></div> : reports.map(report => {
    const professors = report.session.professorIds.map(id => ({ _id: id, name: directory.professors.find(p => p._id === id)?.name || report.rows.flatMap(r => r.observations).find(o => o.observerId === id)?.observerName || t('professor') }));
    return <section className="panel" key={report.session._id}><div className="section-head"><div><h2>{report.session.title}</h2><p>{date(report.session.startAt)} · {time(report.session.startAt)}</p></div></div><AttendanceTable data={{ ...report, professors }}/></section>;
  })}</>;
}

export function AuditPage() {
  const { t, user, date, time, run, busy, directory } = useApp(); const resource = useResource(user.kind === 'admin' ? '/audit' : null); const [detail, setDetail] = useState(null);
  if (user.kind !== 'admin') return <Empty text="noAccess"/>;
  return <><PageTitle title={t('activity')} subtitle={t('activitySub')}/><ResourceState {...resource}><div className="panel">{resource.data?.events.length === 0 ? <Empty text="noActivity"/> : <div className="table-scroll"><table><thead><tr><th>{t('action')}</th><th>{t('actor')}</th><th>{t('time')}</th><th>{t('detail')}</th></tr></thead><tbody>{resource.data?.events.map(e => <tr key={e._id}><td><strong>{t(e.action)}</strong></td><td>{e.actorName}</td><td>{date(e.createdAt)} · {time(e.createdAt)}</td><td><Button variant="ghost" onClick={() => setDetail(e)}>{t('detail')}</Button></td></tr>)}</tbody></table></div>}</div>{resource.data?.next && <Button variant="secondary" disabled={busy} onClick={() => run(async () => { const next = await api(`/audit?before=${encodeURIComponent(resource.data.next)}`); resource.setData({ events: [...resource.data.events,...next.events], next: next.next }); })}>{t('more')}</Button>}</ResourceState>{detail && <Modal title={t(detail.action)} onClose={() => setDetail(null)}><p>{detail.actorName} · {date(detail.createdAt)} · {time(detail.createdAt)}</p>{detail.detail.title && <p>{detail.detail.title}</p>}{detail.detail.role && <p>{t('role')}: {t(detail.detail.role)}</p>}{detail.detail.studentIds && <p>{t('roster')}: {detail.detail.studentIds.map(id => directory.students.find(s => s._id === id)?.name || t('student')).join(' · ')}</p>}{detail.detail.after && <div className="audit-change"><div><small>{t('before')}</small><p>{t(detail.detail.before?.status || 'unmarked')}{detail.detail.before?.isRep !== undefined && ` · ${t(detail.detail.before.isRep ? 'rep' : 'student')}`}</p></div><div><small>{t('after')}</small><p>{detail.detail.after.status && t(detail.detail.after.status)}{detail.detail.after.isRep !== undefined && t(detail.detail.after.isRep ? 'rep' : 'student')}</p>{detail.detail.after.reason && <p>{detail.detail.after.reason}</p>}{detail.detail.after.recordedAt && <small>{t('recorded')}: {date(detail.detail.after.recordedAt)} {time(detail.detail.after.recordedAt)}</small>}</div></div>}</Modal>}</>;
}
